"""empty message

Revision ID: 9283bc99f9cd
Revises: a61427c56304
Create Date: 2023-01-26 19:17:35.491244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9283bc99f9cd'
down_revision = 'a61427c56304'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favoritos', schema=None) as batch_op:
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('personajes_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('planetas_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('vehicles_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favoritos', schema=None) as batch_op:
        batch_op.alter_column('vehicles_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('planetas_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('personajes_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
