"""empty message

Revision ID: a61427c56304
Revises: 1ba9208ee399
Create Date: 2023-01-26 15:18:13.321029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a61427c56304'
down_revision = '1ba9208ee399'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favoritos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planetas_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('vehicles_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'vehicles', ['vehicles_id'], ['id'])
        batch_op.create_foreign_key(None, 'planetas', ['planetas_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favoritos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('vehicles_id')
        batch_op.drop_column('planetas_id')

    # ### end Alembic commands ###
